# Generated by Django 3.0.8 on 2020-07-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
