# Generated by Django 3.0.8 on 2020-07-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20200719_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='desc3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
