# Generated by Django 3.0.8 on 2020-07-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_customer_order_orderitem_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True),
        ),
    ]
