# Generated by Django 3.0.8 on 2020-07-26 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_remove_customer_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
    ]
