# Generated by Django 3.0.8 on 2020-07-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20200727_0001'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
